myname: zhaoguojian
server:
  port: 8080
  servlet:
    context-path: /helloworld
spring:
  jpa: 
    hibernate: 
      ddl-auto: update
    show-sql: true
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/helloworld?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: root
  profiles: 
    active: pro
    
